events {}

http {
    upstream friendlyseat_api {
        server api:8080;
    }
    upstream friendlyseat_admin {
        server admin:8080;
    }

    server {
        listen 80;
        server_name api.example.com;
        client_max_body_size 20m;

        location / {
            proxy_pass http://friendlyseat_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name admin.example.com;

        location / {
            proxy_pass http://friendlyseat_admin;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
